import React, { useState } from 'react';

/**
 * Task interface representing a complete task object in the board state.
 * Aligns with domain glossary and coding standards from memory-banks/.
 *
 * - id: Unique identifier generated by the system
 * - projectId: Reference to the parent project
 * - title: Task name (required, non-empty)
 * - description: Optional task details
 * - status: One of 'todo', 'in-progress', 'done' (must match domain glossary exactly)
 * - createdAt: ISO timestamp when task was created
 * - updatedAt: ISO timestamp when task was last modified
 */
interface Task {
  id: string;
  projectId: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'done';
  createdAt: string;
  updatedAt: string;
}

/**
 * TaskFormProps for the TaskForm component.
 *
 * - projectId: Required ID of the project this task belongs to
 * - onSubmit: Callback when task is successfully created (STORY-001.003 criterion 1)
 * - onCancel: Optional callback for form cancellation
 */
interface TaskFormProps {
  projectId: string;
  onSubmit: (task: Task) => void;
  onCancel?: () => void;
}

/**
 * TaskForm Component
 *
 * Creates a new task in the To Do column of the active project.
 * Implements requirements from STORY-001.003-create-task.md and follows
 * architectural patterns from memory-banks/architecture/overview.md.
 *
 * Acceptance Criteria Implemented:
 * - Criterion 1: User enters title in form and submits → new task appears in To Do
 * - Criterion 2: New task includes id, title, status ('todo') in client-side state
 * - Criterion 3: Empty/whitespace-only title → validation error, task not created
 * - Criterion 4: After successful creation → input cleared for next entry
 *
 * Accessibility:
 * - aria-invalid on input when error state exists
 * - aria-describedby linking error message to input
 * - role="alert" on error message for screen reader announcement
 *
 * Performance Note:
 * - State updates and validation run synchronously (< 100ms target per story)
 * - No side effects for persistence (handled by parent/persistence adapter)
 */
export const TaskForm: React.FC<TaskFormProps> = ({ projectId, onSubmit, onCancel }) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [error, setError] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    // Validation: Title cannot be empty or whitespace-only (STORY-001.003 criterion 3)
    if (!title.trim()) {
      setError('Title is required');
      return;
    }

    setError('');

    // Create task with all required fields (STORY-001.003 criterion 2)
    // Status defaults to 'todo' (To Do column per architecture/overview.md)
    const newTask: Task = {
      id: `task-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      projectId,
      title: title.trim(),
      description: description.trim() || undefined,
      status: 'todo',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    onSubmit(newTask);

    // Clear form for next task entry (STORY-001.003 criterion 4)
    setTitle('');
    setDescription('');
  };

  return (
    <form onSubmit={handleSubmit} className="task-form">
      <div className="form-group">
        <label htmlFor="title">Task Title *</label>
        <input
          id="title"
          type="text"
          value={title}
          onChange={(e) => {
            setTitle(e.target.value);
            if (error) setError('');
          }}
          placeholder="Enter task title"
          aria-invalid={error ? 'true' : 'false'}
          aria-describedby={error ? 'error-message' : undefined}
          required
        />
      </div>

      <div className="form-group">
        <label htmlFor="description">Description</label>
        <textarea
          id="description"
          value={description}
          onChange={(e) => setDescription(e.target.value)}
          placeholder="Enter task description (optional)"
          rows={4}
        />
      </div>

      {error && (
        <div
          id="error-message"
          className="error-message"
          role="alert"
          aria-live="polite"
        >
          {error}
        </div>
      )}

      <div className="form-actions">
        <button type="submit" className="btn btn-primary">
          Create Task
        </button>
        {onCancel && (
          <button type="button" onClick={onCancel} className="btn btn-secondary">
            Cancel
          </button>
        )}
      </div>
    </form>
  );
};

export default TaskForm;
